Update ci-cd-pipeline.yaml
yml changed

diff --git a/.github/workflows/ci-cd-pipeline.yaml b/.github/workflows/ci-cd-pipeline.yaml
--- a/.github/workflows/ci-cd-pipeline.yaml
+++ b/.github/workflows/ci-cd-pipeline.yaml
@@ -3,7 +3,7 @@ name: Run pipeline and build Docker image
 on:
   push:
     branches:
-      - main  # or any other branch you want to monitor
+      - main  # Change this if needed
 
 jobs:
   run-pipeline:
@@ -16,16 +16,21 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: '3.10'  # specify the Python version
+          python-version: '3.x'
 
       - name: Install dependencies
-        run: pip install -r loan_prediction/requirements.txt  # make sure you have a requirements.txt file in the loan_prediction folder
+        run: |
+          if [ -f load_prediction/requirements.txt ]; then
+            pip install -r load_prediction/requirements.txt
+          else
+            echo "requirements.txt not found!" && exit 1
+          fi
 
       - name: Run pipeline.py
-        run: python loan_prediction/pipeline.py
+        run: python load_prediction/pipeline.py
 
   build-docker-image:
-    needs: run-pipeline  # this ensures that this job runs only after 'run-pipeline' succeeds
+    needs: run-pipeline
     runs-on: ubuntu-latest
 
     steps:
@@ -33,12 +38,16 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Build Docker image
-        run: docker build -t my-app:latest loan_prediction/
+        run: docker build -t my-app:latest load_prediction/
 
-      - name: Commit and push changes
+      - name: Check for changes
         run: |
-          git config --global user.name "${{ secrets.GH_USERNAME }}"
-          git config --global user.email "${{ secrets.GH_EMAIL }}"
-          git commit -am "Automated commit message"
-          git remote set-url origin https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com/${{ secrets.GH_USERNAME }}/loan-prediction.git
-          git push origin HEAD:main
+          git status
+          if ! git diff --quiet; then
+            git config --global user.name "${{ secrets.GH_USERNAME }}"
+            git config --global user.email "${{ secrets.GH_EMAIL }}"
+            git add .
+            git commit -m "Automated commit"
+            git push https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
+          else
+            echo "No changes to commit"
